src/ASPLabs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ASPLabs.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/ASPLabs/Controllers/IntegrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ASPLabs.LabsLogic.Integration;
using ASPLabs.ModelViews.Integration;

namespace ASPLabs.Controllers
{
    public class IntegrationController : Controller
    {
        public IActionResult Index()
        {
            return View("InputForm");
        }

        public IActionResult Trapezoidal(IntegrationInput ii)
        {
            Trapezoidal trapezoidal = new Trapezoidal(ii.IntervalsCount);
            trapezoidal.initPoints();
            trapezoidal.CalcIntegral();

            ViewBag.xValues = trapezoidal.DrawPointsX;
            ViewBag.yValues = trapezoidal.DrawPointsY;
            ViewBag.Integral = trapezoidal.Integral;
            ViewBag.Title = "Trapezoidal Integration";
            ViewBag.methodName = "Trapezoidal Integration";
            ViewBag.description = "In mathematics, and more specifically in numerical analysis," +
                "the trapezoidal rule (also known as the trapezoid rule or trapezium rule) is a technique for approximating the definite integral";

            return View();
        }

        public IActionResult SquareTrapezoidal(IntegrationInput ii)
        {
            SquareTrapezoidal sqrTrap = new SquareTrapezoidal(ii.IntervalsCount);
            sqrTrap.Accuracy = ii.Accuracy;
            sqrTrap.initPoints();
            sqrTrap.CalcIntegral();

            ViewBag.xValues = sqrTrap.DrawPointsX;
            ViewBag.yValues = sqrTrap.DrawPointsY;
            ViewBag.Integral = sqrTrap.Integral;

            ViewBag.IT_h = sqrTrap.I_Th;
            ViewBag.ITH = sqrTrap.I_TH[0];
            ViewBag.IPH = sqrTrap.I_PH;
            ViewBag.RTh = sqrTrap.R_h;

            ViewBag.Title = "Rectangle Trapezoidal Integration";
            ViewBag.methodName = "Rectangle Trapezoidal Integration";

            return View();
        }
    }
}

src/ASPLabs/Controllers/InterpolationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ASPLabs.ModelViews.Interpolation;
using ASPLabs.LabsLogic.Interpolation;
namespace ASPLabs.Controllers
{
    public class InterpolationController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View("InputForm");
        }

        public IActionResult Lagrange(InterpolationInput ii)
        {
            List<double> xValues;
            List<double> yValues;
            List<double> controlPoints;
            try
            {
                xValues = VectorParser.ParseFromString(ii.xValues);
                yValues = VectorParser.ParseFromString(ii.yValues);
                controlPoints = VectorParser.ParseFromString(ii.controlPoints);
            }
            catch (ArgumentNullException e)
            {
                return View("ERROR! Invalid arguments!");
            }

            Lagrange lg = new Lagrange(xValues, yValues, controlPoints);

            InterpolationOutput io = new InterpolationOutput();
            io.xKeys = controlPoints;
            io.yValues = lg.CalculateAll();

            ViewBag.Title = "Lagrange Interpolation";
            ViewBag.methodName = "Lagrange polynomial";
            ViewBag.description = "In numerical analysis, Lagrange polynomials are used for polynomial interpolation";
            ViewBag.xValues = xValues;
            ViewBag.yValues = yValues;
            lg.initLagrangePoints();
            ViewBag.xLagrange = lg.xLagrange;
            ViewBag.yLagrange = lg.yLagrange;

            return View("Lagrange", io);
        }

        public IActionResult Gauss(InterpolationInput ii)
        {
            List<double> controlPoints;
            double step = 0;
            try
            {
                controlPoints = VectorParser.ParseFromString(ii.controlPoints);
            }
            catch (ArgumentNullException e)
            {
                return View("ERROR! Invalid arguments!");
            }

            Gauss st = new Gauss(controlPoints);
            st.CalculateAll();

            InterpolationOutput io = new InterpolationOutput();
            io.xKeys = controlPoints;
            io.yValues = st.CalculateAll();


            ViewBag.xValues = st._xValues;
            ViewBag.yValues = st._yValues;
            st.initGaussPoints();
            ViewBag.xGauss = st.xGauss;
            ViewBag.yGauss = st.yGauss;

            ViewBag.Title = "Gauss Interpolation";
            ViewBag.methodName = "Gauss Forward/Back polynomial";
            ViewBag.description = "Gaussian process is a powerful non-linear interpolation tool. Many popular interpolation tools are actually equivalent to particular Gaussian processes";

            return View(io);
        }

        public IActionResult Stirling(InterpolationInput ii)
        {
            List<double> controlPoints;
            double step = 0;
            try
            {
                controlPoints = VectorParser.ParseFromString(ii.controlPoints);
            }
            catch (ArgumentNullException e)
            {
                return View("ERROR! Invalid arguments!");
            }

            Stirling st = new Stirling(controlPoints);
            st.CalculateAll();

            InterpolationOutput io = new InterpolationOutput();
            io.xKeys = controlPoints;
            io.yValues = st.CalculateAll();

            ViewBag.xValues = st._xValues;
            ViewBag.yValues = st._yValues;
            st.initStirlingPoints();
            ViewBag.xStirling = st.xStirling;
            ViewBag.yStirling = st.yStirling;

            ViewBag.Title = "Stirling Interpolation";
            ViewBag.methodName = "Stirling Interpolation";
            ViewBag.description = "Stirling’s formula is used for the interpolation of functions for values of x close to one of the middle nodes a";

            return View(io);
        }

        public IActionResult NewtonMethod(InterpolationInput ii)
        {
            List<double> controlPoints;
            double step = 0;
            try
            {
                controlPoints = VectorParser.ParseFromString(ii.controlPoints);
            }
            catch (ArgumentNullException e)
            {
                return View("ERROR! Invalid arguments!");
            }

            Newton nt = new Newton(controlPoints);


            InterpolationOutput io = new InterpolationOutput();
            io.xKeys = controlPoints;
            io.yValues = nt.CalculateAll();

            ViewBag.Title = "Newton Interpolation";
            ViewBag.methodName = "Newton Interpolation First Formula";
            ViewBag.description = "The Newton polynomial is sometimes called Newton's divided differences interpolation polynomial because the coefficients of the polynomial are calculated using divided differences";
            ViewBag.xValues = nt._xValues;
            ViewBag.yValues = nt._yValues;
            nt.initNewtonPoints();
            ViewBag.xNewton = nt.xNewton;
            ViewBag.yNewton = nt.yNewton;

            return View("NewtonMethod", io);
        }
    }
}

src/ASPLabs/Views/EigenValuesMethods/InputMatrix.cshtml
@model MatrixInput
<form asp-controller="EigenValuesMethods" asp-action=@ViewBag.Action method="post" class="form-group" style="margin: 0 auto; max-width: 300px">
    <input asp-for="Accuracy" id="accuracy" class="form-control" placeholder="Accuracy" style="max-width: 300px; margin-top: 10px" value="0.5">
    <textarea asp-for="MatrixString" type="text" class="form-control" placeholder="Matrix" style="height: 300px; max-height: 300px; max-width: 300px; float:left; margin-top: 10px"></textarea>
    <button type="submit" class="btn btn-primary" style="margin-top: 10px">Submit</button>
</form>
<div id="spinner">
</div>

src/ASPLabs/Views/EigenValuesMethods/MethodCalcsOutput.cshtml
@model MethodResults

<div class="jumbotron">
    <h1>@ViewBag.methodName</h1>
    <p>
        @ViewBag.description
    </p>
</div>
<h2>Matrix</h2>
<table class="table table-hover table-bordered">
    <tbody>
         @for (int i = 0; i < Model.matrix.Count; i++)
            {
        <tr>
           

                @for (int j = 0; j < Model.matrix[i].Count; j++)
                {
                    <td align="center">
                        @Model.matrix[i][j]
                    </td>
                }
        </tr>
         }
    </tbody>
</table>

<h2>Steps</h2>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Iteration</th>
            <th>Vector Y</th>
            <th> Lambda</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.IterationsCount; i++)
            {
            <tr>
                <td align="center">@i</td>
                <td align="center">(
                    @foreach (double val in Model.stepVectorsY[i])
                    {
                        @val <tag>|</tag>
                    }
                )</td>
                <td align="center">@Model.lambdas[@i]</td>
            </tr>
        }
    </tbody>
</table>

<h2>Result Information</h2>
<strong>Excecution time:</strong> @Model.ExecutionTime<br />
<strong>Iterations count:</strong> @Model.IterationsCount<br />
<strong>Eigenvalue:</strong> @Model.PairsList[0].eigenValue;<br />
<strong>EigenVector:</strong>(@foreach (double val in Model.PairsList[0].eigenVector)
{
    @val <tag>|</tag>
})

src/ASPLabs/Views/Integration/InputForm.cshtml
@model IntegrationInput

<form asp-controller="Integration" asp-action="InputProcess" method="post" class="form-group input-form" style="margin: 0 auto; max-width: 1000px">

    <div class="options">
        <div class="radio">
            <label><input type="radio" name="optradio" value="Trapezoidal" checked="checked">Trapezoidal Integration</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="optradio" value="SquareTrapezoidal">SquareTrapezoidal</label>
        </div>
    </div>
    <div>
        <img name="formula" src="~/img/formula-integration.PNG" />
        <input asp-for="IntervalsCount" type="text" class="form-control" placeholder="Intervals Count">
        <input asp-for="Accuracy" type="text" class="form-control" placeholder="Accuracy" value="0.000000001">
    </div>
    <button type="submit" class="btn btn-primary" style="margin-top: 10px" onclick="selectRoute()">Submit</button>
</form>

<script>
    function selectRoute() {
        var route = $('input[name="optradio"]:checked').val();
        $('form').attr("action", "/Integration/" + route);
    }
</script>

<style>
    .input-form textarea {
        max-height: 350px;
        height: 350px;
        max-width: 300px;
        float: left;
        margin-top: 10px;
        margin: 5px;
    }

    .input-form input {
        max-width: 300px;
        margin-top: 10px;
        margin: 5px;
    }

    .options {
        max-width: 200px;
    }
</style>

src/ASPLabs/Views/Integration/SquareTrapezoidal.cshtml
<div class="jumbotron">
    <h1>@ViewBag.methodName</h1>
    <p>
        @ViewBag.description
    </p>
</div>


<div>
    <script type="text/javascript"
            src="https://www.google.com/jsapi?autoload={
            'modules':[{
              'name':'visualization',
              'version':'1',
              'packages':['corechart']
            }]
          }">
    </script>

    <script type="text/javascript">
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var jScriptArray = new Array(@ViewBag.xValues.Count);
            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                jScriptArray[i] = new Array(2);
            }

            @for (int i = 0; i < ViewBag.xValues.Count; i++)
            {
                <text>
            jScriptArray[@i][0] = "@ViewBag.xValues[@i]";
            jScriptArray[@i][1] = "@ViewBag.yValues[@i]";

            </text>
            }


            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn('number', 'x');
            dataTable.addColumn('number', 'f(x)');

            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                var t = parseFloat(jScriptArray[i][0]);
                var d = parseFloat(jScriptArray[i][1]);
                dataTable.addRow([t, d]);
            }

            var options = {
                title: 'Function Plot',
                curveType: 'function',
                legend: { position: 'bottom' },
                series: {
                    0: { lineWidth: 2 },
                    1: { lineWidth: 2 }
                },
                colors: ['#e2431e', '#d3362d'],

                width: 1200, height: 600,
                vAxis: {
                    title: 'f(x)',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 20,
                    }

                },
                hAxis: {
                    title: 'x',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 100,
                    }
                }
            };
            var chart = new google.visualization.LineChart(document.getElementById('myPieChart'));
            chart.draw(dataTable, options);
        }
    </script>
</div>

<div id="myPieChart"></div>

<h1>
    Result: <strong>@ViewBag.Integral</strong>
</h1>


<h2>Steps</h2>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>I^T (H)</th>
            <th>I^P (H)</th>
            <th>I^T (h)</th>
            <th>R^T (h)</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < ViewBag.IPH.Count; i++)
        {
            <tr>
                <td align="center">@i</td>
                <td align="center">
                    @ViewBag.ITH
                </td>
                <td align="center">
                    @ViewBag.IPH[i]
                </td>
                <td align="center">
                    @ViewBag.IT_h[i]
                </td>
                <td align="center">
                    @ViewBag.RTh[i]
                </td>
            </tr>
        }
    </tbody>
</table>

src/ASPLabs/Views/Integration/Trapezoidal.cshtml
<div class="jumbotron">
    <h1>@ViewBag.methodName</h1>
    <p>
        @ViewBag.description
    </p>
</div>


<div>
    <script type="text/javascript"
            src="https://www.google.com/jsapi?autoload={
            'modules':[{
              'name':'visualization',
              'version':'1',
              'packages':['corechart']
            }]
          }">
    </script>

    <script type="text/javascript">
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var jScriptArray = new Array(@ViewBag.xValues.Count);
            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                jScriptArray[i] = new Array(2);
            }

            @for (int i = 0; i < ViewBag.xValues.Count; i++)
            {
                <text>
            jScriptArray[@i][0] = "@ViewBag.xValues[@i]";
            jScriptArray[@i][1] = "@ViewBag.yValues[@i]";

            </text>
            }


            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn('number', 'x');
            dataTable.addColumn('number', 'f(x)');

            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                var t = parseFloat(jScriptArray[i][0]);
                var d = parseFloat(jScriptArray[i][1]);
                dataTable.addRow([t, d]);
            }

            var options = {
                title: 'Function Plot',
                curveType: 'function',
                legend: { position: 'bottom' },
                series: {
                    0: { lineWidth: 2 },
                    1: { lineWidth: 2 }
                },
                colors: ['#e2431e', '#d3362d'],

                width: 1200, height: 600,
                vAxis: {
                    title: 'f(x)',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 20,
                    }

                },
                hAxis: {
                    title: 'x',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 100,
                    }
                }
            };
            var chart = new google.visualization.LineChart(document.getElementById('myPieChart'));
            chart.draw(dataTable, options);
        }
    </script>
</div>

<div id="myPieChart"></div>

<h2>
    Result: <strong>@ViewBag.Integral</strong>
</h2>

src/ASPLabs/Views/Interpolation/Gauss.cshtml
@model InterpolationOutput

<div class="jumbotron">
    <h1>@ViewBag.methodName</h1>
    <p>
        @ViewBag.description
    </p>
</div>


<div>
    <script type="text/javascript"
            src="https://www.google.com/jsapi?autoload={
            'modules':[{
              'name':'visualization',
              'version':'1',
              'packages':['corechart']
            }]
          }">
    </script>

    <script type="text/javascript">
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var jScriptArray = new Array(@ViewBag.xValues.Count);
            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                jScriptArray[i] = new Array(2);
            }

            @for (int i = 0; i < ViewBag.xValues.Count; i++)
            {
                <text>
            jScriptArray[@i][0] = "@ViewBag.xValues[@i]";
            jScriptArray[@i][1] = "@ViewBag.yValues[@i]";

            </text>
            }


            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn('number', 'x');
            dataTable.addColumn('number', 'f(x)');

            for (var i = 0; i < @ViewBag.xValues.Count; i++) {
                var t = parseFloat(jScriptArray[i][0]);
                var d = parseFloat(jScriptArray[i][1]);
                dataTable.addRow([t, d]);
            }

            var options = {
                title: 'Function Plot',
                curveType: 'function',
                legend: { position: 'bottom' },
                series: {
                    0: { lineWidth: 2 },
                    1: { lineWidth: 2 }
                },
                colors: ['#e2431e', '#d3362d'],

                width: 1200, height: 600,
                vAxis: {
                    title: 'f(x)',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 20,
                    }

                },
                hAxis: {
                    title: 'x',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 100,
                    }
                }
            };
            var chart = new google.visualization.LineChart(document.getElementById('myPieChart2'));
            chart.draw(dataTable, options);
        }
    </script>

    <script type="text/javascript">
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var jScriptArray = new Array(@ViewBag.xGauss.Count);
            for (var i = 0; i < @ViewBag.xGauss.Count; i++) {
                jScriptArray[i] = new Array(2);
            }

            @for (int i = 0; i < ViewBag.xGauss.Count; i++)
            {
                <text>
            jScriptArray[@i][0] = "@ViewBag.xGauss[@i]";
            jScriptArray[@i][1] = "@ViewBag.yGauss[@i]";

            </text>
            }


            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn('number', 'x');
            dataTable.addColumn('number', 'f(x)');

            for (var i = 0; i < @ViewBag.xGauss.Count; i++) {
                var t = parseFloat(jScriptArray[i][0]);
                var d = parseFloat(jScriptArray[i][1]);
                dataTable.addRow([t, d]);
            }

            var options = {
                title: 'Gauss Polynom Plot',
                curveType: 'function',
                legend: { position: 'bottom' },
                series: {
                    0: { lineWidth: 2 },
                    1: { lineWidth: 2 }
                },
                colors: ['#d3362d', '#d3362d'],

                width: 1200, height: 600,
                vAxis: {
                    title: 'f(x)',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 20,
                    }

                },
                hAxis: {
                    title: 'x',
                    viewWindowMode: 'explicit',
                    gridlines: {
                        count: 100,
                    }
                }
            };
            var chart = new google.visualization.LineChart(document.getElementById('myPieChart'));
            chart.draw(dataTable, options);
        }
    </script>
</div>

<div id="myPieChart2"></div>
<div id="myPieChart"></div>

<h2>Results</h2>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>X Control</th>
            <th>Y</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.xKeys.Count; i++)
        {
            <tr>
                <td align="center">@i</td>
                <td align="center">
                   @Model.xKeys[@i]
                </td>
                <td align="center">
                   @Model.yValues[@i]
                </td>
            </tr>
        }
    </tbody>
</table>

src/ASPLabs/Views/Interpolation/InputForm.cshtml
@model InterpolationInput
<form asp-controller="Interpolation" asp-action="InputProcess" method="post" class="form-group input-form" style="margin: 0 auto; max-width: 1000px">

    <div class="options">
        <div class="radio">
            <label><input type="radio" name="optradio" value="Lagrange" checked="checked" onchange="handleChange()">Lagrange Interpolation</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="optradio" value="NewtonMethod" onchange="handleChange()">Newton Interpolation Formula 1</label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="optradio" value="Gauss" onchange="handleChange()">Gauss Interpolation Methods(Forward or back is defined on the given value)
            </label>
        </div>
        <div class="radio">
            <label><input type="radio" name="optradio" value="Stirling" onchange="handleChange()">Stirling</label>
        </div>
    </div>
    <div>
        <img name="formula" src="~/img/formula.PNG" />
        <textarea asp-for="xValues" type="text" class="form-control" placeholder="X Points"></textarea>
        <textarea asp-for="yValues" type="text" class="form-control" placeholder="Y Points"></textarea>
        <textarea asp-for="controlPoints" type="text" class="form-control" placeholder="Control Points"></textarea>
    </div>
    <button type="submit" class="btn btn-primary" style="margin-top: 10px" onclick="selectRoute()">Submit</button>
</form>

<script>
    $(document).ready(function () {
        $('img[name=formula]').hide();
    });

    function handleChange() {
        var route = $('input[name="optradio"]:checked').val();
        if (route != "Lagrange") {
            $('textarea[name=yValues]').hide();
            $('textarea[name=xValues]').hide();
            $('img[name=formula]').show();
        }
        else {
            $('textarea[name=xValues]').show();
            $('textarea[name=yValues]').show();
            $('img[name=formula]').hide();
        }

    }

    function selectRoute() {
        var route = $('input[name="optradio"]:checked').val();
        $('form').attr("action", "/Interpolation/" + route);
    }
</script>

<style>
    .input-form textarea {
        max-height: 350px;
        height: 350px;
        max-width: 300px;
        float: left;
        margin-top: 10px;
        margin: 5px;
    }

    .input-form input {
        max-width: 300px;
        margin-top: 10px;
        margin: 5px;
    }

    .options {
        max-width: 200px;
    }
</style>

src/ASPLabs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/layout.css" rel="stylesheet" />
</head>

<body>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


    <div class="page-header">
        <img src="~/img/logo.png" width="125" height="125" />
        <img src="~/img/logo-name.png" />
    </div>

    <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="./" class="navbar-brand">Home</a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">Getting started</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">RGR Eigenvalues/Eigenvectors <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Power Method", "PowerMethod", "EigenValuesMethods")</li>
                            <li>@Html.ActionLink("Scalar Product Method", "ScalarProductMethod", "EigenValuesMethods")</li>
                            <li>@Html.ActionLink("Power Aitken Method", "PowerAitkenMethod", "EigenValuesMethods")</li>
                            <li><a href="#">Gauss–Seidel method</a></li>
                            <li><a href="#">Successive over-relaxation</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Interpolation", "Index", "Interpolation")</li>
                    <li>@Html.ActionLink("Numerical Integration", "Index", "Integration")</li>
                </ul>
            </nav>
        </div>
    </header>

    <div>
        @RenderBody()
    </div>
</body>
</html>